### ISSUE TITLE
Post page

### ISSUE THREAD

**Issue by Razielt77** [codefresh-io/blog#12]
![inpost](https://cloud.githubusercontent.com/assets/7720348/8273700/134943f2-182d-11e5-883f-c38f43e9ea1f.png)

you can see a sample post in our current blog at http://blog.codefresh.io/getting-started-with-codefresh-labs/

![2015-06-21_15-47-34](https://cloud.githubusercontent.com/assets/7720348/8273701/2088a90e-182d-11e5-86f5-62516903e904.png)

**Comment by tgolen** [comment]
I will fix the title font size and margin.

The inline images look to be the same size as the current blog, so I'm not sure what to recommend for a size.

The addition of the header image is going to be too large to be in the scope of this first phase and I request that we push it until later.

**Comment by Razielt77** [comment]
sounds good. we can push the image for next version

**Comment by tgolen** [comment]
![image](https://cloud.githubusercontent.com/assets/1228807/8390313/08d92f6e-1c4b-11e5-9ef1-21cbe23d130b.png)

**Comment by Razielt77** [comment]
This looks better thanks.. I will check promptly on my machine and will close it

**Comment by Razielt77** [comment]
it does look better. can we force the images in the post to have the same width of the text section (and keep the proportions). at the moment the images are spread wider than the text

**Comment by tgolen** [comment]
I have made the images the same width as the text.

Note: this is not how it is on the current blog.
